name = "itsu-dev-oekaki"
main = "src/index.tsx"
compatibility_date = "2023-08-23"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "itsu-dev-oekaki-db"
database_id = "746b28d0-bd2a-46a7-828d-f1b5e44498ef"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'itsu-dev-oekaki-images'
preview_bucket_name = 'itsu-dev-oekaki-images'